version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - back-end/.env
    ports:
      - 5432:5432
    networks:
      - my-network
  frontend:
    image: node:16
    working_dir: /app
    command: bash -c "npm install && npm run build && npm run dev -- -p 1337"
    volumes:
      - ./front-end:/app
    ports:
      - "1337:1337"
    env_file:
      - front-end/.env
    networks:
      - my-network

  backend:
    image: node:16
    working_dir: /app
    command: bash -c "npm install && npm run build && npx prisma migrate dev --name update && npm run start:dev"
    volumes:
      - ./back-end:/app
    ports:
      - "3000:3000"
      - "5555:5555"
    networks:
      - my-network
    depends_on: 
      - db

networks:
  my-network:
